@startuml tollgate-context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Context diagram for Toll gate system

Person(user, "User")
System(tgs, "Toll gate system")

Rel_R(user, tgs, "passes through")

SHOW_LEGEND()

@enduml