name: Generate PlantUML Diagrams
on:
  push: 
    branches:
      - main

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@1.2021.1
        with:
          args: -v -tsvg docs/**.puml

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          skip_dirty_check: true
          skip_checkout: true
          push_options: '--force'
      